{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "uberentityservice",
    "version": "0.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "uberentityservice-0.0.3-SNAPSHOT-plain.jar",
          "url": "uberentityservice-0.0.3-SNAPSHOT-plain.jar",
          "size": 28778,
          "sha512": "e78b529802d23b31fea667f481d75ee2a3841a88a614ccff5882b61d505a3908513c72dd3b0c1b836aab39deb6cdfb45e12062df262fa700a8d9af4cd66e083c",
          "sha256": "3bcf15f54646fdcb9ea44edf44d8a4adcf040742df7056fb640d2c6df364be2c",
          "sha1": "04518b34d74d5832d33b45f26e1ace6cb15cd008",
          "md5": "39122dbf92bcd37ff8cd8f993dbb8524"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j"
        }
      ],
      "files": [
        {
          "name": "uberentityservice-0.0.3-SNAPSHOT-plain.jar",
          "url": "uberentityservice-0.0.3-SNAPSHOT-plain.jar",
          "size": 28778,
          "sha512": "e78b529802d23b31fea667f481d75ee2a3841a88a614ccff5882b61d505a3908513c72dd3b0c1b836aab39deb6cdfb45e12062df262fa700a8d9af4cd66e083c",
          "sha256": "3bcf15f54646fdcb9ea44edf44d8a4adcf040742df7056fb640d2c6df364be2c",
          "sha1": "04518b34d74d5832d33b45f26e1ace6cb15cd008",
          "md5": "39122dbf92bcd37ff8cd8f993dbb8524"
        }
      ]
    }
  ]
}
