{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "uberentityservice",
    "version": "0.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "uberentityservice-0.0.4-SNAPSHOT-plain.jar",
          "url": "uberentityservice-0.0.4-SNAPSHOT-plain.jar",
          "size": 29878,
          "sha512": "8ba8b3b9a66907631ff90d61a36bcb608e82ca8dec63ce9e122020dbc0aba5b0e5b3e5f811a2884d0fd7507ad8429b859a813ce3a2615e7700bebc6bc65a7d2b",
          "sha256": "6bdba0e65bbd67bd96adf51c3a95416b1bdabee8f7ab0cd55385f83401020012",
          "sha1": "f06db277b12b1b72a3f29ac570ef07e554e64387",
          "md5": "8a65dae40cecc823d904889010aa8a4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j"
        }
      ],
      "files": [
        {
          "name": "uberentityservice-0.0.4-SNAPSHOT-plain.jar",
          "url": "uberentityservice-0.0.4-SNAPSHOT-plain.jar",
          "size": 29878,
          "sha512": "8ba8b3b9a66907631ff90d61a36bcb608e82ca8dec63ce9e122020dbc0aba5b0e5b3e5f811a2884d0fd7507ad8429b859a813ce3a2615e7700bebc6bc65a7d2b",
          "sha256": "6bdba0e65bbd67bd96adf51c3a95416b1bdabee8f7ab0cd55385f83401020012",
          "sha1": "f06db277b12b1b72a3f29ac570ef07e554e64387",
          "md5": "8a65dae40cecc823d904889010aa8a4f"
        }
      ]
    }
  ]
}
